[package]
name = "concord-verifier"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
concord-core = { path = "../core" }
concord-constraints = { path = "../constraints" }
concord-scanner = { path = "../scanner" }
concord-project = { path = "../project" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
