[package]
name = "concord-scanner"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
concord-core = { path = "../core" }
sysinfo = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
